name: Portofolio React

on:
  push:
    branches: 
      - main
      
jobs:
 build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          # cache: 'yarn' # Speeds up installs by caching dependencies

      - name: run postcss
        run:
          yarn upgrade @babel/core --latest
          yarn upgrade react-scripts --latest
          yarn add react@18 react-dom@18

      - name: Install react router dom
        run: yarn add react-router-dom
        
      - name: Install Dependencies
        run: yarn install

      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Run ESLint without blocking build
        run: yarn lint --max-warnings=999 || true

      - name: Build Project
        run: NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: Deploy to Vercel
        run: yarn global add vercel && vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
  
